### ISSUE TITLE
wrapping long return-adresses

### ISSUE THREAD

**Issue by pschmidtwalter** [rnuske/komaletter#10]
A long return-adress defined in the YAML-header is wrapped into multiple lines. An probably undesired effect is that (after printing and careful folding) only the lowest line of the return-adress can be seen  in the adress window of a standard envelope. The rest is hidden.

**Comment by rnuske** [comment]
The default layout of the Koma-Script letter class 'scrlttr2', used by komaletter, does not handle two-line backaddresses well. It sticks out at the top of the address window and the baseline distance is way too large.

See also related [TeX StackExchange Question](https://tex.stackexchange.com/q/550092/218581)

**Comment by rnuske** [comment]
Commit 13a4f0b introduces a new dependency on LaTeX Package `ragged2e`. I hought about making the usage of ragged2e conditional on presence of `ragged2e.sty`. Sine `tinytex` would not install the needed ragged2e package if it is not a hard dependency, I decided to keep it as a hard dependency.

not used in `maintainersDelight.lco`
```
\IfFileExists{ragged2e.sty}{\usepackage{ragged2e}}{}
```
and further down
```
\IfFileExists{ragged2e.sty}{\RaggedRight}{\raggedright}%
```
