### ISSUE TITLE
Double sender address

### ISSUE THREAD

**Issue by fergusjchadwick** [rnuske/komaletter#11]
Thanks for developing this great package. Is there any way to prevent the sender address from appearing twice (under the name and above the recipient address). I'd ideally like to only feature the sender address in the top right.

**Comment by rnuske** [comment]
This is actually a design decision for the default letter layout. The return address above the recipients address shall be visible through envelope's window so no manual marking of the envelope is needed.

I've got two ideas how to tackle your problem:

1) You could create your own variant of the default letter layout (`inst/rmarkdown/templates/pdf/resources/maintainersDelight.lco`) and look at vignette (`vignettes/letter_example1.Rmd`) how to use it.

2) A simpler way but rather a **hack**: You could use the new YAML variable `return-short` in the github version of komaletter (currently on its way to CRAN) and set it to something not visible but not a "non-empty" value (" " did not work for me, but the non-breaking space did). This will create a new, not visible address above the recipients address, e.g.
```
---
author: Max Mustermann
return-address: 
  - Musterstr. 12
  - 34567 Musterstadt
address:
  - Robert Nuske
  - Hauptstr. 31
  - 30167 Hannover
  - Germany
return-short: "\u00a0"
```

I would really love if `return-short: " "` would do the job. But the the check in my version of [pandoc's](https://pandoc.org/MANUAL.html#conditionals) template.tex (`inst/rmarkdown/templates/pdf/resources/template.tex`) whether return-short is set and should be acted on interprets `" "` as not non-empty. 

Any help with improving the behaviour of this check would be very welcome!

Did this lengthy answer help you?

**Comment by fergusjchadwick** [comment]
This worked! Thanks so much for the time and effort in your reply. It's good to know that there's a purpose to this feature and that a more robust change is possible. I wasn't confident enough with markdown to dive into the template but if I get a chance to rewrite it I'll be sure to put in a pull request in case it's of interest to others.

**Comment by rnuske** [comment]
Thanks for your feedback!
