### ISSUE TITLE
hyperlinked text print the url as a footnote

### ISSUE THREAD

**Issue by Hanomics** [rnuske/komaletter#12]
Thank you for developing this interesting package. 
Is there any way to produce a hyperlinked text without printing the URL as a footnote? I want to produce a clickable text. 
Here is a snapshot of the following code line produces:
`[linked text here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)`

![hyperlink](https://user-images.githubusercontent.com/65606367/87061965-57633a80-c204-11ea-9b9b-f9a4ee96756e.png)

**Comment by rnuske** [comment]
I'm very sorry I haven't seen your question for so long. Somehow I have misconfigured my github account and it does not notify me about new issues.

There is a currently undocumented YAML parameter `inline-links` which causes the links to be hotlinks in the PDF document. But the link is not styled differently at the moment.

So technically just set `inline-links: true` in your YAML header.


I will document that parameter on the help page of the R Function and think about styling of links. What do you think about just bold text for the "linked text" or maybe a monospace font?

**Comment by rnuske** [comment]
@Hanomics
I added documentation, some styling and an example in vignette `letter_example2.Rmd` (63eb616). Please test the github version and let me know what you think about the styling.

**Comment by Hanomics** [comment]
Brilliant! Thank you so much for this - very much appreciated.
