### ISSUE TITLE
Error linked to polyglossia’s `\setmainlanguage` – Switch to babel recommended

### ISSUE THREAD

**Issue by njbart** [rnuske/komaletter#18]
This file,

```
---
lco: DIN
lang: fr
author: John Doe
return-address: 
  - Address 1
  - Address 1
return-email: doe@example.com
return-phone: +01 234 567890
address:
  - Rob Recipient
subject: The Subject
opening: Opening
closing: Closing
mainfont: "Avenir Next"
sansfont: "Avenir Next"
output: 
  komaletter::komaletter:
    latex_engine: xelatex
---

Text.
```

knit from within RStudio (details below) fails with the message

```
==> rmarkdown::render('/Users/nb/letters/test.Rmd',  encoding = 'UTF-8');


processing file: test.Rmd
  |......................................................................| 100%
  ordinary text without R code


output file: test.knit.md

/usr/local/bin/pandoc +RTS -K512m -RTS test.knit.md --to latex --from markdown+tex_math_single_backslash-autolink_bare_uris --output test.tex --lua-filter /Library/Frameworks/R.framework/Versions/4.2/Resources/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.2/Resources/library/rmarkdown/rmarkdown/lua/latex-div.lua --embed-resources --standalone --template /Library/Frameworks/R.framework/Versions/4.2/Resources/library/komaletter/rmarkdown/templates/pdf/resources/template.tex --highlight-style tango --pdf-engine xelatex '--variable=lco_default:/Library/Frameworks/R.framework/Versions/4.2/Resources/library/komaletter/rmarkdown/templates/pdf/resources/maintainersDelight' 
! Argument of \str_uppercase:n has an extra }.
<inserted text> 
                \par 
l.46   \setmainlanguage[]{}

Error: LaTeX failed to compile test.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See test.log for more info.
Execution halted
```

(Output is as expected if `lang: fr` is removed.)

The error message suggests that the underlying problem might be the use of the polyglossia package no longer supported by more recent versions of pandoc – see https://github.com/JensErat/pandoc-scrlttr2/issues/20 and https://github.com/Wandmalfarbe/pandoc-latex-template/issues/278. Conclusion from these reports: A switch to the babel package is recommended.

---

R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_6_8) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

komaletter 0.4.2

**Comment by rnuske** [comment]
Thanks for reporting. I was wondering why this problem does not occur with me, since I also use komaletter in the current RStudio with a non-English language. The difference seems to be, that I do not use `xelatex`. This is also discussed at JensErat/pandoc-scrlttr2#20.

I removed the xelatex part of the language setting in template.tex following the changes in the general pandoc template in jgm/pandoc@f4d2c9e.

Please test this change with your setup and your letter.

**Comment by njbart** [comment]
Excellent. Works wholly as expected now. Many thanks.

**Comment by rnuske** [comment]
Thanks for the feedback. Will try to release a new Version on CRAN soon.
