### ISSUE TITLE
Avoid number of pages (from page 2)

### ISSUE THREAD

**Issue by LuisLauM** [rnuske/komaletter#21]
Thank you very much for the package, it is really very useful. I know that usually a letter is only composed of a single page. However, when the body exceeds this limit (e.g. up to 2 pages), from the second page onwards the page number is shown at the bottom of each sheet. Of course this can be avoided by editing the `.tex` template, but I leave the suggestion to make this a default feature. Thank you!

**Comment by rnuske** [comment]
Hi @LuisLauM 
Thanks for reaching out. I think page numbers for letters with more than one page are standard in formal letter writing. So i will keep page numbers as the default. As you mentioned it would bei possible to introduce a new parameter to switch page numbering off. As I currently have very little time, I cannot implement it myself, but would accept a pull request.
